### ISSUE TITLE
Question regarding sound...

### ISSUE THREAD

**Issue by everythingability** [SableRaf/Shadertoy2Processing#2]
You haven't figured out how to pass FFT to a shader yet have you?

I'm trying to pass audio to https://www.shadertoy.com/view/MtyyDw 

Thanks

Tom

p.s I'm kinda here:

import ddf.minim.*;
import ddf.minim.analysis.*;
Minim minim=new Minim(this); 
AudioSample mySound;
FFT fft;
String soundFileName="/Users/tomsmith/Desktop/Donald Trump defends Paul Manafort 'He happens to be a very good person'.mp3";
int avgSize=12000;

void fft_setup(){

  mySound = minim.loadSample(soundFileName, 4194304); //I tried to load the entire song into buffer big enough
  mySound.trigger(); //Seems like I have to play the sound for FFT to work?
 
  fft = new FFT(mySound.bufferSize(), mySound.sampleRate());
  fft.forward(mySound.mix); 
}

///// WITH THIS IN MY DRAW METHOD /////

 println( fft.getAverageCenterFrequency(440) );
  
  myShader.set("iChannel0", fft.getAverageCenterFrequency(440));

////AND THIS IN MY SHADER
uniform sampler2D iChannel0;
uniform sampler2D iChannel1;

**Comment by SableRaf** [comment]
Hi Tom,

The audio is passed as a 512x2 texture where the first line is the FFT represented as greyscale values (actually a single channel color but I don't know how to do this in Processing), and the second line is the "wave information" (I'm not sure what this is supposed to be). You can read more about this in [this example](https://www.shadertoy.com/view/Xds3Rr) from Shadertoy.

I started reproducing the same example in Processing. It's not fully there yet (only FFT for now), but it might be helpful: https://github.com/SableRaf/Shadertoy2Processing/commit/896fda7589760ef6504de26650a2d281c401bd48

Have a great day :)

**Comment by bmFicg** [comment]
?

// **first row is frequency data (48Khz/4 in 512 texels, meaning 23 Hz per texel)**
``` float fft  = texelFetch( iChannel0, ivec2(tx,0), 0 ).x;```

[https://p5js.org/reference/#/p5.FFT/analyze](https://p5js.org/reference/#/p5.FFT/analyze)

// **second row is the sound wave, one texel is one mono sample**
``` float wave = texelFetch( iChannel0, ivec2(tx,1), 0 ).x;```

[https://p5js.org/reference/#/p5.FFT/waveform](https://p5js.org/reference/#/p5.FFT/waveform)

- - -

https://www.openprocessing.org/sketch/673110

**Comment by hamoid** [comment]
> the first line is the FFT represented as greyscale values (actually a single channel color but I don't know how to do this in Processing), and the second line is the "wave information"

As far as I know, the first row is the left channel and the bottom row is the right channel.

**Comment by bmFicg** [comment]
@hamoid  nOob :)

edit: their is not simply way to get left/right channel out of WebAudio to pipe that data into FFT
https://developer.mozilla.org/en-US/docs/Web/API/AnalyserNode
https://stackoverflow.com/questions/37642144/web-audio-api-get-getbytetimedomaindata-for-left-right-channel-in-two-arrays

**Comment by SableRaf** [comment]
To clarify (a little bit at least), based on this comment from @huttarl over in the comments of the [Shadertoy basic sound example](https://www.shadertoy.com/view/Xds3Rr), this is what the two rows of the sound texture are supposed to be:

> Looks like, in the frequency data, the x (or u) axis of the texture is the frequency (scaled to the 0-to-1 interval). And the color of the texture there, or at least the first component of it, is the strength of the sound at that frequency? Is there a spec about this somewhere?
> 
> Similarly, in the wave data (second row), the x (or u) axis of the texture is the X axis of the waveform over this tiny slice of time (scaled to the 0-to-1 interval). And the color of the texture there, or at least the first component of it, is the y axis of the waveform.

Inigo Quilez (creator of Shadertoy) confirmed in the following comment that this description was correct. I still don't understand, but that's the most in depth explanation I could find :)

The description of the shader says:
> The sound is uploaded as a 512x2 texture. First row is the spectrum, second one is the waveform.

**Comment by hamoid** [comment]
Ah I see, so I thought it was Left/Right instead of FFT / Waveform.

In that case, you can take a look at 

    Examples > Libraries > Sound > Analysis > AudioWaveform

or

    Examples > Contributed Libraries > Minim > AudioPlayer > loop

Both examples visualize the audio data, which is what the second row of pixels provides in ShaderToy.

**Comment by bmFicg** [comment]
Judging just by my personal experience and have no valid source to backup my assumption:  
I would say becource releases by Major Labels the end-user would always served with the [mono compatibility](https://resoundsound.com/mono-compatibility/ ) at least on the key elements of a soundtrack such as lead voice or kick. And second: back in time when WebAudio was indroduced Intel Pentium 4 [Firefox 25 Spec](https://www.mozilla.org/en-US/firefox/25.0/system-requirements/ ) was still round, satisfy the decision have FFT-data as a down-mixed version. Which is just fine targeting to create „something nice“ on a visual performance. 
A priori: In process of composition, recording and mixing a soundtrack to execute FFT on Left -Right channel is key, by means the observed precision inherits an equally result when the audio is [mastered](https://en.wikipedia.org/wiki/Mastering_(audio))   

+ Exampel (modern mastered tracks)
  + On average the difference on Left / Right is trivial [Larger then life ](https://www.youtube.com/results?search_query=pop+songs+2018) 
+ Counter Example: guitar left, guitar delay effect right
  + One of thouse songs where a split of right left channel in a visual performance would make totally sense [Black Sabbath -Electric Funeral ](https://youtu.be/Z0C9CvlWKKY?t=1441)

Cheers :v:
